const fs = require("fs");
import { parse } from "csv-parse";
import { stringify } from "csv-stringify";

let wordA = "";
let wordB = "";
const TAGS = [
  "Aquatic",
  "Cologne",
  "Any Occasion",
  "Amber",
  "Anti-bacterial",
  "All Skin Types",
  "Acne",
  "Balm",
  "Creme",
  "Above 30",
  "Anti Ageing",
  "Acetone-Free",
  "Acetone-Free",
  "Acetone-Free",
  "Chemically & Heat Damaged Hair",
  "Cream",
  "Almond",
  "Ammonia Free",
  "Ammonia Free",
  "Ammonia Free",
  "Chemically Treated",
  "Creme",
  "Full",
  "Balm",
  "Curling",
  "Acetone-Free",
  "Acetone-Free",
  "Acetone-Free",
  "Above 30",
  "Combination",
  "Acne & Blemishes",
  "Almond Oil",
  "Lavender",
  "Balm & Butter",
  "Liquid",
  "Floral",
  "Above 30",
  "Acne Removal",
  "Almond",
  "Acetone-Free",
  "Acetone-Free",
  "Acetone-Free",
  "Acetone-Free",
  "Acetone-Free",
  "Acne & Blemishes",
  "Long",
  "Under 1000W",
  "3M to 1Y",
  "Argan Coating / Plating",
  "Body",
  "Yes",
  "Outright Buy",
  "Premium",
  "Male",
  "Floral",
  "Deodrants",
  "Casual",
  "Anise",
  "Anti-perspirant",
  "Combination",
  "Antioxidant Support",
  "Bar",
  "Gel",
  "Below 15",
  "Brightening",
  "Alcohol-Free",
  "Alcohol-Free",
  "Alcohol-Free",
  "Colour Protect",
  "Gel",
  "Aloe Vera",
  "Cold Pressed",
  "Cold Pressed",
  "Cold Pressed",
  "Curly",
  "Demi Matte",
  "Light",
  "Breathable",
  "Cuticle Care",
  "Alcohol-Free",
  "Alcohol-Free",
  "Alcohol-Free",
  "Below 30",
  "Dry",
  "Anti Ageing",
  "Argan Oil",
  "Peppermint",
  "Capsule",
  "Oil",
  "Fresh",
  "Below 15",
  "Anti odour",
  "Aloe Vera",
  "Alcohol-Free",
  "Alcohol-Free",
  "Alcohol-Free",
  "Alcohol-Free",
  "Alcohol-Free",
  "Anti-Pollution",
  "Medium",
  "1000W to 1500W",
  "1Y to 2Y",
  "Diamond Ceramic Coating / Plating",
  "Face",
  "No",
  "Marketplace",
  "Mastige",
  "Female",
  "Fresh",
  "EDP",
  "Day Wear",
  "Basil",
  "Brightening",
  "Dry",
  "Blackheads",
  "Capsule",
  "Liquid",
  "Between 15-30",
  "Fairness",
  "Allergy-Free",
  "Allergy-Free",
  "Allergy-Free",
  "Damaged Hair",
  "Liquid",
  "Argan Oil",
  "Herbal",
  "Herbal",
  "Herbal",
  "Dull Hair",
  "Dewy",
  "Medium",
  "Crayon",
  "Growth Boosting",
  "Ammonia-Free",
  "Ammonia-Free",
  "Ammonia-Free",
  "SPF 50+",
  "Normal",
  "Anti-Cavity",
  "Castor Oil",
  "Rosemary",
  "Cream",
  "Spray",
  "Fruity & Citrus",
  "Between 15-30",
  "Anti-Ageing",
  "Argan Oil",
  "Ammonia-Free",
  "Ammonia-Free",
  "Ammonia-Free",
  "Ammonia-Free",
  "Ammonia-Free",
  "Color Protection",
  "Short",
  "1500W to 2000W",
  "More than 2Y",
  "Infrared Plates",
  "Hair",
  "Consignment",
  "Luxury",
  "Unisex",
  "Fruity",
  "EDT",
  "Evening Wear",
  "Bergamot",
  "Long-lasting",
  "Normal",
  "Dark Circles",
  "Cream",
  "Mist",
  "SPF 50+",
  "Hydrating",
  "Ammonia-Free",
  "Ammonia-Free",
  "Ammonia-Free",
  "Dandruff",
  "Mask",
  "Avacado",
  "Highlight & fashion",
  "Highlight & fashion",
  "Highlight & fashion",
  "Fine",
  "Duochrome",
  "Sheer",
  "Cream",
  "Hydrating",
  "Animal Hair",
  "Animal Hair",
  "Animal Hair",
  "No SPF",
  "Oily",
  "Anti-Pollution",
  "Coconut Oil",
  "Tea Tree",
  "Foam",
  "Roll-on",
  "Sweet",
  "SPF 50+",
  "Anti-Bacterial",
  "Avacado",
  "Animal Hair",
  "Animal Hair",
  "Animal Hair",
  "Anti-Inflammatory",
  "Anti-Inflammatory",
  "Dandruff",
  "Above 2000W",
  "Keratin Coating / Plating",
  "Head to Toe",
  "Leather",
  "Gas",
  "Everyday Essentials",
  "Cardamom",
  "Stain-Free",
  "Oily",
  "Dehydrated Skin",
  "Foam",
  "No SPF",
  "Light Weight",
  "Anti-Inflammatory",
  "Anti-Inflammatory",
  "Anti-Inflammatory",
  "Dry Hair",
  "Mousse",
  "Beetroot",
  "Mineral-Oil free",
  "Mineral-Oil free",
  "Mineral-Oil free",
  "Grey Hair",
  "Gel",
  "Translucent",
  "Gel",
  "Lengthening",
  "Anti-Inflammatory",
  "Anti-Inflammatory",
  "Anti-Inflammatory",
  "Sensitive",
  "Bacteria",
  "Grapeseed Oil",
  "Gel",
  "Stick",
  "Warm & Spicy",
  "No SPF",
  "Anti-Cavity",
  "Beeswax",
  "Anti-Inflammatory",
  "Anti-Inflammatory",
  "Anti-Inflammatory",
  "Antioxidants",
  "Antioxidants",
  "Dark Spots/Pigmentation",
  "Steam Plates",
  "Oud",
  "Liquid",
  "Formal",
  "Cedarwood",
  "Sensitive",
  "Dryness",
  "Gel",
  "Long Lasting",
  "Antioxidants",
  "Antioxidants",
  "Antioxidants",
  "Dull Hair",
  "Oil",
  "Castor Oil",
  "Natural",
  "Natural",
  "Natural",
  "Normal",
  "Glitter",
  "Transparent",
  "Liquid",
  "Long Lasting",
  "Antioxidants",
  "Antioxidants",
  "Antioxidants",
  "Callus",
  "Kumkumadi Oil",
  "Liquid",
  "Pocket",
  "Woody & Earthy",
  "Anti-perspirant",
  "Beetroot",
  "Antioxidants",
  "Antioxidants",
  "Antioxidants",
  "Clinically Proven",
  "Clinically Proven",
  "Dry Hair",
  "Titanium Coating / Plating",
  "Sweet",
  "Mist",
  "Party",
  "Cinnamon",
  "Dull Skin",
  "Lotion/Body Butter",
  "Key Ingredients",
  "Moisturising",
  "Clinically Proven",
  "Clinically Proven",
  "Clinically Proven",
  "Fine/Thin Hair",
  "Powder",
  "Chamomile",
  "Naturally Fortified",
  "Naturally Fortified",
  "Naturally Fortified",
  "Oily",
  "Glossy",
  "Loose Powder",
  "Moisturizing",
  "Cruelty-Free",
  "Cruelty-Free",
  "Cruelty-Free",
  "Chapped Lips",
  "Lavender Oil",
  "Lotion",
  "Calming",
  "Castor Oil",
  "Bio-Degradable",
  "Bio-Degradable",
  "Bio-Degradable",
  "Collagen",
  "Collagen",
  "Dull Hair",
  "Tourmaline Coating / Plating",
  "Vanilla",
  "Oils",
  "Special Occasion",
  "Gernanium",
  "Inflammation",
  "Mask",
  "AHA",
  "Nourishing",
  "Cruelty-Free",
  "Cruelty-Free",
  "Cruelty-Free",
  "Frizzy Hair",
  "Serum",
  "Charcoal",
  "Non Greasy",
  "Non Greasy",
  "Non Greasy",
  "Straight",
  "Luminous/Radiant",
  "Mousse",
  "Non Clumping",
  "Dermatologically Tested",
  "Dermatologically Tested",
  "Dermatologically Tested",
  "Cracked heels",
  "Moringa Oil",
  "Mist",
  "Cooling",
  "Chamomile",
  "Chlorine-Free",
  "Chlorine-Free",
  "Chlorine-Free",
  "Cruelty-Free",
  "Cruelty-Free",
  "Fine Lines & Wrinkles",
  "Warm & Spicy",
  "Roll on",
  "Sporty",
  "Grapefruit",
  "Large/Clogged Pores",
  "Mist",
  "Almond",
  "Waterproof",
  "Dermacosmetic",
  "Dermacosmetic",
  "Dermacosmetic",
  "Grey Hair",
  "Spray",
  "Clay",
  "Non-sticky",
  "Non-sticky",
  "Non-sticky",
  "Thick",
  "Matte",
  "Oil",
  "Oil Control",
  "Formaldehyde-Free",
  "Formaldehyde-Free",
  "Formaldehyde-Free",
  "Cuticle Care",
  "Morrocan Oil",
  "Oil",
  "Fresh Breath",
  "Charcoal",
  "Clinically Proven",
  "Clinically Proven",
  "Clinically Proven",
  "Dermatologically Tested",
  "Dermatologically Tested",
  "Firming",
  "Woody & Earthy",
  "Jasmine",
  "Look of Redness",
  "Mousse",
  "Aloe Vera",
  "Formaldehyde-Free",
  "Formaldehyde-Free",
  "Formaldehyde-Free",
  "Hairfall",
  "Wax",
  "Coconut",
  "Organic",
  "Organic",
  "Organic",
  "Thin",
  "Metallic",
  "Peelable",
  "Plumping",
  "Fragrance-Free",
  "Fragrance-Free",
  "Fragrance-Free",
  "Dark Spot/Pigmentation",
  "Olive Oil",
  "Paste",
  "Freshening",
  "Coconut",
  "Colour-Free",
  "Colour-Free",
  "Colour-Free",
  "Formaldehyde-Free",
  "Formaldehyde-Free",
  "Frizzy Hair",
  "Lavender",
  "Oily Skin",
  "Oil-Based",
  "Alpha Arbutin",
  "Fragrance-Free",
  "Fragrance-Free",
  "Fragrance-Free",
  "Heat Protection",
  "Eucalyptus",
  "Paraben Free",
  "Paraben Free",
  "Paraben Free",
  "Wavy",
  "Multi",
  "Pen",
  "Quick Dry",
  "Gluten-Free",
  "Gluten-Free",
  "Gluten-Free",
  "Dead skin",
  "Others",
  "Powder",
  "Germ protection",
  "Combination",
  "Cruelty-Free",
  "Cruelty-Free",
  "Cruelty-Free",
  "Fragrance-Free",
  "Fragrance-Free",
  "Hairfall",
  "Leather",
  "Pigmentation",
  "Pack",
  "Antioxidants",
  "Gluten-Free",
  "Gluten-Free",
  "Gluten-Free",
  "Oil Control",
  "Green Tea",
  "Sticky",
  "Sticky",
  "Sticky",
  "Natural",
  "Pencil",
  "Repairing",
  "Halal",
  "Halal",
  "Halal",
  "Dry skin",
  "Rosehip Oil",
  "Roll-On",
  "Hydrating",
  "Eucalyptus",
  "Dermatolgically tested",
  "Dermatolgically tested",
  "Dermatolgically tested",
  "Gluten-Free",
  "Gluten-Free",
  "Heat Protection",
  "Lemon",
  "Puffiness",
  "Powder",
  "Argan Oil",
  "Halal Certified",
  "Halal Certified",
  "Halal Certified",
  "Oily Hair",
  "Honey",
  "Sulphate Free",
  "Sulphate Free",
  "Sulphate Free",
  "Satin",
  "Pressed Powder",
  "Strengthening",
  "Herbal",
  "Herbal",
  "Herbal",
  "Dullness",
  "Tea Tree Oil",
  "Scrub",
  "Lightening/Whitening",
  "Green Tea",
  "Ergonomic design",
  "Ergonomic design",
  "Ergonomic design",
  "Herbal",
  "Herbal",
  "Hydration",
  "Lemon Grass",
  "Sun protection",
  "Scrub",
  "Avacado",
  "Herbal",
  "Herbal",
  "Herbal",
  "Rough Hair",
  "Jojoba Oil",
  "Shimmer",
  "Roll-on",
  "Transfer Proof",
  "Hypoallergenic",
  "Hypoallergenic",
  "Hypoallergenic",
  "Firming",
  "Sponge",
  "Long-lasting",
  "Honey",
  "Formaldehyde-Free",
  "Formaldehyde-Free",
  "Formaldehyde-Free",
  "Home",
  "Home",
  "Oil Control",
  "Mandarin",
  "Uneven Skintone",
  "Serum",
  "Beeswax",
  "Japanese Beauty",
  "Japanese Beauty",
  "Japanese Beauty",
  "Scalp Care",
  "Lemon Grass",
  "Application",
  "Special Effects",
  "Serum",
  "Transfer Resistant",
  "Mineral Oil-Free",
  "Mineral Oil-Free",
  "Mineral Oil-Free",
  "Hydration",
  "Spray",
  "Moisturising",
  "Jojoba Oil",
  "Fragrance-Free",
  "Fragrance-Free",
  "Fragrance-Free",
  "Hypoallergenic",
  "Hypoallergenic",
  "Overly Fine Hair/Thin Hair",
  "Alcohol Free",
  "Mint",
  "Wrinkles",
  "Sponge",
  "Beetroot",
  "Korean Beauty",
  "Korean Beauty",
  "Korean Beauty",
  "Split Ends",
  "Moringa",
  "Prewash",
  "Tinted",
  "Spray",
  "Volumising",
  "Natural",
  "Natural",
  "Natural",
  "Ingrowth",
  "Stick",
  "Non greasy",
  "Lemon Grass",
  "Germ Resistant",
  "Germ Resistant",
  "Germ Resistant",
  "Mineral Oil-Free",
  "Mineral Oil-Free",
  "Pores/Black Heads/White Heads",
  "Yes",
  "Moss",
  "Stick",
  "Castor Oil",
  "Mineral Oil-Free",
  "Mineral Oil-Free",
  "Mineral Oil-Free",
  "Tangled Hair",
  "Neem",
  "Wash",
  "Stick",
  "Waterproof",
  "Non-Comedogenic",
  "Non-Comedogenic",
  "Non-Comedogenic",
  "Oil Control",
  "Wax",
  "Pain Relief",
  "Moringa",
  "Gluten-Free",
  "Gluten-Free",
  "Gluten-Free",
  "Natural",
  "Natural",
  "Product Build-Up",
  "No",
  "Musk",
  "Water-Based",
  "Chamomile",
  "Natural",
  "Natural",
  "Natural",
  "Thin Hair",
  "Niacinimai",
  "Post Wash",
  "Oil Free",
  "Oil Free",
  "Oil Free",
  "Pores/Blackheads/Whiteheads",
  "Plague control",
  "Neem",
  "Halal Certified",
  "Halal Certified",
  "Halal Certified",
  "Non-Comedogenic",
  "Non-Comedogenic",
  "Stretch Marks",
  "Neroli",
  "Wax",
  "Charcoal",
  "Non-Comedogenic",
  "Non-Comedogenic",
  "Non-Comedogenic",
  "Papaya",
  "Leave in",
  "Opthalmologically Tested",
  "Opthalmologically Tested",
  "Opthalmologically Tested",
  "Rough skin",
  "Refreshing",
  "Niacinamide",
  "Herbal",
  "Herbal",
  "Herbal",
  "Ophthamologically-Free",
  "Ophthamologically-Free",
  "Sun Protection",
  "Orange",
  "Wipes",
  "Clay",
  "Non-Vegetarian",
  "Non-Vegetarian",
  "Non-Vegetarian",
  "Pomegranate",
  "Organic",
  "Organic",
  "Organic",
  "Stretch Marks",
  "Rejuvinating",
  "Papaya",
  "Hypoallergenic",
  "Hypoallergenic",
  "Hypoallergenic",
  "Organic",
  "Organic",
  "Tan Removal",
  "Others",
  "Liquid",
  "Coconut",
  "Nut-Free",
  "Nut-Free",
  "Nut-Free",
  "Rose",
  "Material",
  "Paba-Free",
  "Paba-Free",
  "Paba-Free",
  "Sun Protection",
  "Relaxing",
  "Pomegranate",
  "Mineral Oil-Free",
  "Mineral Oil-Free",
  "Mineral Oil-Free",
  "Paraben-Free",
  "Paraben-Free",
  "Tangled Hair",
  "Oud",
  "Copper Peptides",
  "Oil-Free",
  "Oil-Free",
  "Oil-Free",
  "Salicylic Acid",
  "Aluminium",
  "Paraben-Free",
  "Paraben-Free",
  "Paraben-Free",
  "Tan Removal",
  "Sensitivity Relief",
  "Rose",
  "Natural",
  "Natural",
  "Natural",
  "Paraben-Free",
  "Paraben-Free",
  "Under Eye Concern",
  "Patchouli",
  "Direct Acids",
  "Ophthamologically Tested",
  "Ophthamologically Tested",
  "Ophthamologically Tested",
  "Sandal wood",
  "Glue",
  "Paraffin-Free",
  "Paraffin-Free",
  "Paraffin-Free",
  "Tender feet",
  "Skin Repair",
  "Salicylic Acid",
  "Non-Comedogenic",
  "Non-Comedogenic",
  "Non-Comedogenic",
  "Paraffin-Free",
  "Paraffin-Free",
  "Uneven Skintone",
  "Pepper",
  "Eucalyptus",
  "Organic",
  "Organic",
  "Organic",
  "Shea Butter",
  "Natural Hair",
  "Proplyene-Free",
  "Proplyene-Free",
  "Proplyene-Free",
  "Under Eye Concern",
  "Sleep Aid",
  "Sandalwood",
  "Odour Control",
  "Odour Control",
  "Odour Control",
  "Professional",
  "Professional",
  "Waterproof",
  "Pine",
  "Glycerin",
  "PABA-Free",
  "PABA-Free",
  "PABA-Free",
  "Squalene",
  "Sponge",
  "Pthalate-Free",
  "Pthalate-Free",
  "Pthalate-Free",
  "Uneven Skintone",
  "Soft skin",
  "Shea Butter",
  "Oil Free",
  "Oil Free",
  "Oil Free",
  "Pthalate-Free",
  "Pthalate-Free",
  "Rose",
  "Green Tea",
  "Paraben-Free",
  "Paraben-Free",
  "Paraben-Free",
  "Sunflower",
  "Synthetic Hair",
  "Silicone-Free",
  "Silicone-Free",
  "Silicone-Free",
  "Soothing/Pain relief",
  "Squalene",
  "Opthalmologically Tested",
  "Opthalmologically Tested",
  "Opthalmologically Tested",
  "Salon",
  "Salon",
  "Sandalwood",
  "Honey",
  "Paraffin-Free",
  "Paraffin-Free",
  "Paraffin-Free",
  "Tea Tree",
  "SLS-Free",
  "SLS-Free",
  "SLS-Free",
  "Stain-free",
  "Sunflower",
  "Organic",
  "Organic",
  "Organic",
  "Silicone-Free",
  "Silicone-Free",
  "Vanilla",
  "Hyaluronic Acid",
  "Petrochemical-Free",
  "Petrochemical-Free",
  "Petrochemical-Free",
  "Turmeric",
  "Soap-Free",
  "Soap-Free",
  "Soap-Free",
  "Stress Reducing",
  "Tea Tree",
  "Paba-Free",
  "Paba-Free",
  "Paba-Free",
  "SLS-Free",
  "SLS-Free",
  "Ylang-Ylang",
  "Hydrators",
  "Phalate-Free",
  "Phalate-Free",
  "Phalate-Free",
  "Vitamin A",
  "Sulphate-Free",
  "Sulphate-Free",
  "Sulphate-Free",
  "Stretch Mark Reduction",
  "Turmeric",
  "Paraben-Free",
  "Paraben-Free",
  "Paraben-Free",
  "Sulphate-Free",
  "Sulphate-Free",
  "Jojoba Oil",
  "Propleyne-Free",
  "Propleyne-Free",
  "Propleyne-Free",
  "Vitamin C",
  "Synthetic Color-Free",
  "Synthetic Color-Free",
  "Synthetic Color-Free",
  "Strong Gums",
  "Vitamin A",
  "Paraffin-Free",
  "Paraffin-Free",
  "Paraffin-Free",
  "Synthetic Color-Free",
  "Synthetic Color-Free",
  "Lemon Grass",
  "Silicon-Free",
  "Silicon-Free",
  "Silicon-Free",
  "Vitamin E",
  "Vegan",
  "Vegan",
  "Vegan",
  "Tan Removal",
  "Vitamin C",
  "Proplyene-Free",
  "Proplyene-Free",
  "Proplyene-Free",
  "Vegan",
  "Vegan",
  "Moringa",
  "SLS-Free",
  "SLS-Free",
  "SLS-Free",
  "Vegetarian",
  "Vegetarian",
  "Vegetarian",
  "Whitening",
  "Vitamin E",
  "Pthalate-Free",
  "Pthalate-Free",
  "Pthalate-Free",
  "Vegetarian",
  "Vegetarian",
  "Neem",
  "Soap-Free",
  "Soap-Free",
  "Soap-Free",
  "Water Resistant",
  "Water Resistant",
  "Water Resistant",
  "Rash-Free",
  "Rash-Free",
  "Rash-Free",
  "Waterproof",
  "Waterproof",
  "Niacinamide",
  "Sulphate-Free",
  "Sulphate-Free",
  "Sulphate-Free",
  "Waterproof",
  "Waterproof",
  "Waterproof",
  "Reusable",
  "Reusable",
  "Reusable",
  "Oils",
  "Synthetic",
  "Synthetic",
  "Synthetic",
  "Silicone-Free",
  "Silicone-Free",
  "Silicone-Free",
  "Papaya",
  "Synthetic Color-Free",
  "Synthetic Color-Free",
  "Synthetic Color-Free",
  "SLS-Free",
  "SLS-Free",
  "SLS-Free",
  "Peptides",
  "Vegan",
  "Vegan",
  "Vegan",
  "Soap-Free",
  "Soap-Free",
  "Soap-Free",
  "Pomegranate",
  "Water Resistant",
  "Water Resistant",
  "Water Resistant",
  "Sulphate-Free",
  "Sulphate-Free",
  "Sulphate-Free",
  "Retinols",
  "Waterproof",
  "Waterproof",
  "Waterproof",
  "Synthetic Color-Free",
  "Synthetic Color-Free",
  "Synthetic Color-Free",
  "Rose",
  "NA",
  "NA",
  "NA",
  "Vegan",
  "Vegan",
  "Vegan",
  "Salicylic Acid",
  "Vegetarian",
  "Vegetarian",
  "Vegetarian",
  "Sandalwood",
  "Water Resistant",
  "Water Resistant",
  "Water Resistant",
  "Shea Butter",
  "Waterproof",
  "Waterproof",
  "Waterproof",
  "Squalane",
  "Sunflower",
  "Tea Tree",
  "Turmeric",
  "Vitamin A",
  "Vitamin C",
  "Vitamin E",
];

let memo = Array.from({ length: 20 }, () => new Array(20).fill(0));

function compareStrings(a: string, b: string): number {
  if (a.length === 0 && b.length === 0) {
    return 0;
  }

  if (a.length === 0) {
    return b.length;
  }

  if (b.length === 0) {
    return a.length;
  }

  if (a[0] === b[0]) {
    return (
      memo[wordA.length - a.length][wordB.length - b.length] +
      compareStrings(a.slice(1), b.slice(1))
    );
  }
  let res =
    memo[wordA.length - a.length][wordB.length - b.length] +
    Math.min(
      compareStrings(a.slice(1), b) + 1,
      compareStrings(a, b.slice(1)) + 1,
      compareStrings(a.slice(1), b.slice(1)) + 1
    );
  return (memo[wordA.length - a.length][wordB.length - b.length] =
    res as never);
}

function testOneDescription(desc: string) {
  const words = desc
    .replace(/[.,\/#!$%\^&\*;:{}=\_~()]/g, " ")
    .split(" ")
    .filter((v) => v.length > 3);

  //   words.forEach((word) => {
  //     wordA = word;
  //     Object.entries(existedTags).forEach((en) => {
  //       en[1].forEach((e) => {
  //         memo = Array.from({ length: 20 }, () => new Array(20).fill(0));
  //         wordB = e;
  //         if (
  //              compareStrings(word.toLocaleLowerCase(), e.toLocaleLowerCase()) <= 1
  //         ) {
  //           console.log(word, e);
  //         }
  //       });
  //     });
  //   });
  const uniqueTags = new Set<string>();
  words.forEach((word) => {
    TAGS.forEach((tag) => {
      if (word.toLocaleLowerCase() === tag.toLocaleLowerCase()) {
        uniqueTags.add(tag);
      }
    });
  });
  return Array.from(uniqueTags);
}

function main() {
  let content = [];
  fs.createReadStream("./pd.csv")
    .pipe(parse({ delimiter: ",", from_line: 2 }))
    .on("data", (row) => {
      let keys = testOneDescription(row[1]);
      content.push([row[0], keys.join(",")]);
    })
    .on("end", () => {
      stringify(content, {}, (err, output) => {
        if (err) throw err;
        fs.writeFile("my.csv", output, (err) => {
          if (err) throw err;
          console.log("my.csv saved.");
        });
      });
    });
}

main();
